from . import (
    ping,
    echo,
    set,
    get,
    rpush,
    llen,
    lrange,
    lpush,
    lpop,
    blpop,
    type,
    xadd,
    xrange,
    xread,
)

COMMANDS = {
    b"PING": ping.execute,
    b"ECHO": echo.execute,
    b"SET": set.execute,
    b"GET": get.execute,
    b"RPUSH": rpush.execute,
    b"LLEN": llen.execute,
    b"LRANGE": lrange.execute,
    b"LPUSH": lpush.execute,
    b"LPOP": lpop.execute,
    b"BLPOP": blpop.execute,
    b"TYPE": type.execute,
    b"XADD": xadd.execute,
    b"XRANGE": xrange.execute,
    b"XREAD": xread.execute,
}
